<Project>
    <!-- If u do git releases then it will override this but if u local build then it will use this i dunno -->
    <PropertyGroup>
        <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
        <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">0.0.0.0</AssemblyVersion>
        <FileVersion Condition="'$(FileVersion)' == ''">0.0.0.0</FileVersion>
    </PropertyGroup>
</Project>
